name = "optidomains-testnet-indexer"
main = "src/index.ts"
compatibility_date = "2023-02-27"

[vars]
  SUPABASE_KEY = ""
  DATA_TABLE = ""
  BACKEND_PK = ""
  ETH_ARCHIVE_NODE = ""

[env.dev]
  [env.dev.vars]
    SUPABASE_KEY = ""
    DATA_TABLE = ""
    BACKEND_PK = ""
    ETH_ARCHIVE_NODE = ""


[triggers]
crons = [ "* * * * *" ]
